version: "3"
services:

  # GraphQLs
  graphql:
    build: ./
    ports:
      - "3000:3000"
    environment:
      USERS_ENDPOINT: "http://spread_daenerys:4000"
      USER_ENDPOINT: "http://id_alfred:3000"

  zipkin:
    image: openzipkin/zipkin:latest@sha256:b5bc35a84201273009d80971651bbdc9380c60f96be672f6f939feaa3689cf6b
    ports:
      - "9411:9411"

  # ID-Services
  id_alfred:
    image: danielmschmidt/zipkin-playground-id:latest@sha256:d57fca9ce7a8e6ce4d1ff6ca45d045709d2df910f4114504b6fd42db0722459a
    ports:
      - "3001:3000"
    environment:
      ZIPKIN_HOST_PORT: "http://zipkin:9411"
      SERVICE: "id-alfred"

  id_batman:
    image: danielmschmidt/zipkin-playground-id:latest@sha256:d57fca9ce7a8e6ce4d1ff6ca45d045709d2df910f4114504b6fd42db0722459a
    ports:
      - "3002:3000"
    environment:
      ZIPKIN_HOST_PORT: "http://zipkin:9411"
      SERVICE: "id-batman"
  
  id_catwoman:
    image: danielmschmidt/zipkin-playground-id:latest@sha256:d57fca9ce7a8e6ce4d1ff6ca45d045709d2df910f4114504b6fd42db0722459a
    ports:
      - "3003:3000"
    environment:
      ZIPKIN_HOST_PORT: "http://zipkin:9411"
      SERVICE: "id-catwoman"

  spread_daenerys:
    image: danielmschmidt/zipkin-playground-spread:latest@sha256:50b137fac1e1c48c3e77ae79a918267f51a79c4e65769adc2b3f9f12910ee263
    ports:
      - "4001:4000"
    environment:
      ZIPKIN_HOST_PORT: "http://zipkin:9411"
      SERVICE: "spread-daenerys"
  
  spread_eddard_stark:
    image: danielmschmidt/zipkin-playground-spread:latest@sha256:50b137fac1e1c48c3e77ae79a918267f51a79c4e65769adc2b3f9f12910ee263
    ports:
      - "4002:4000"
    environment:
      ZIPKIN_HOST_PORT: "http://zipkin:9411"
      SERVICE: "spread-eddard-stark"